name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ENV_EMAIL_BACKEND: $ENV_EMAIL_BACKEND
  ENV_EMAIL_HOST: $ENV_EMAIL_HOST
  ENV_EMAIL_HOST_PASSWORD: $ENV_EMAIL_HOST_PASSWORD
  ENV_EMAIL_HOST_USER: ENV_EMAIL_HOST_USER
  ENV_EMAIL_PORT: ENV_EMAIL_PORT
  ENV_EMAIL_USE_TLS: $ENV_EMAIL_USE_TLS

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install pipenv
        pipenv install
    - name: Run Tests
      run: |
        pipenv run test
